<?php

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = '
(function(w,d){
    var lS = function(a,b){ a.readyState?a.onreadystatechange=function(){(a.readyState==\'loaded\'||a.readyState==\'complete\')&&(a.onreadystatechange=null,b());}:a.onload=function(){b();};},
    bR = w.require,
    rQS = \'requirejs-src\',
    rdQS = \'requirejs-dep-src\',
    rJs = d.querySelector(`[${rQS}]`),
    rJd = d.querySelectorAll(`[${rdQS}]`),
    cS = (s,a) => { s.src=s.getAttribute(a);s.removeAttribute(a); },
    tE = [\'keydown\',\'mouseover\',\'touchstart\'],
    rP = new Promise(r => {
        var rF = function() { w.__dcr = w.require = w.requirejs; r(); };
        w.hasOwnProperty(\'requirejs\') && rF();
        var eC = function(){
            tE.forEach(e => { d.removeEventListener(e, eC, false); });
            var u = lS(rJs, () => {
                w.require = w.requirejs;
                p = [];
                rJd.forEach(s => {
                    p.push(new Promise(ld => { lS(s,ld); }));
                });
                Promise.all(p).then(rF);
                rJd.forEach(f => { cS(f,rdQS); });
            });
            w.requirejs = bR;
            cS(rJs,rQS);
        };
        tE.forEach(e => { d.addEventListener(e, eC, false); });
        setTimeout(eC,5000);
    });
    w.__dcr = require = function(a,b,c,d) {
        return rP.then(() => {
            w.require(Array.isArray(a)? a:[a],b,c,d);
        });
    };
    w.require = require.config = require;
    })(window, document);
    ';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
